[hangman_bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
[hangman_bot] Waiting for 3 seconds before continuing (required by "messages.EditMessage")
Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
Traceback (most recent call last):
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/HangMan/Hangman.py", line 687, in hint_callback
    await callback_query.answer(f"Hint: The word contains the letter '{hint}'")
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 159, in answer
    return await self._client.answer_callback_query(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/bots/answer_callback_query.py", line 73, in answer_callback_query
    return await self.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/methods/advanced/invoke.py", line 79, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 389, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/session/session.py", line 357, in send
    RPCError.raise_it(result, type(data))
  File "/home/ubuntu/miniforge3/envs/bots/lib/python3.11/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
